export enum SCREEN_NAME {
    MENU = 'MENU🏁',
    NATIVE_GESTURE = 'NATIVE_GESTURE👈',
    REANIMATE_GESTURE = 'REANIMATE_GESTURE🙌',
    SHARED_NAV = 'SHARED_NAV🦈',
    TF_CAMERA = 'TF_CAMERA📸',
    SCROLL_ANIMATE = 'SCROLL_ANIMATE📜',
    SCROLL_ANIMATE_HORIZONT = 'SCROLL_ANIMATE_HORIZONT📜',
    SORT_ANIMATE = 'SORT_ANIMATE📆',
    PAN_ROTATE_SQUARE = 'PAN_ROTATE_SQUARE🟩',
    PAN_ROTATE_CIRCLE = 'PAN_ROTATE_CIRCLE🔘',
    SVG_START = 'SVG_START🫀',
    MODAL_STACK_NAV = 'MODAL_STACK_NAV⚙️',
}

